Plugin external metadata_edns0
coredns/metadata_edns0 pull request #1
Opened 2019-01-24 12:44 UTC by rajansandeep

Initial commit
Needs CI tests.

2019-01-29 02:15 UTC, fturib requested changes
Some few changes before we can merge this first version.
Then we will need to add the CI and some tests running, including a test with a real execution of ServeDNS with ctx and data in the query.

2019-01-29 02:15 UTC, fturib commented on README.md
> +So far, only 'hex' format is supported with params <length> <start> <end>
That comment seems wrong to me. you have three format supported. However only `hex` has extra parameters

2019-01-29 02:15 UTC, fturib commented on metadata_edns0.go
> +		return nil
I think you should not return nil here, but `ctx`. See plugin metadata, function `ServeDNS`

2019-01-30 19:42 UTC, rajansandeep commented
@fturib I addressed your comments.
I'll merge this now.

2019-01-30 19:42 UTC, merged